kind: Cluster
apiVersion: cluster.x-k8s.io/v1beta1
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ include "cluster-api-kamaji-vsphere.cluster-name" . | quote }}
  name: {{ include "cluster-api-kamaji-vsphere.cluster-name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KamajiControlPlane
    name: {{ include "cluster-api-kamaji-vsphere.cluster-name" . }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereCluster
    name: {{ include "cluster-api-kamaji-vsphere.cluster-name" . }}