{{- if .Values.vSphere.secret.create }}
---
kind: Secret
apiVersion: v1
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ include "cluster-api-kamaji-vsphere.cluster-name" $ | quote }}
  name: {{ include "cluster-api-kamaji-vsphere.vsphere-secret-name" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ .Values.vSphere.password | quote }}
  username: {{ .Values.vSphere.username | quote }}
{{- end }}

